# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Contacts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Contacts
pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'

end
